---
seafile_servers: seafile_servers
cops_seafile_name: "seafile"
cops_seafile_tld_domain: "example.net"
cops_seafile_hostname:  "{{cops_seafile_name}}.{{cops_seafile_tld_domain}}"
cops_seafile_alternate_hostnames: ["{{cops_seafile_hostname}}", "www.{{cops_seafile_hostname}}"]
cops_seafile_gitref: "{{lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_seafile_docker_tag: "{{cops_seafile_gitref.replace('master', 'latest')}}"
cops_seafile_docker_env_extra: |-
  # db
