---
- file:
    state: directory
    mode: "2751"
    path: "{{item}}"
  with_items:
  - "{{cops_seafile_dir}}"
- template:
    src: "onlyoffice.env"
    dest: "{{cops_seafile_compose_dir}}/onlyoffice.env"
    mode: "0640"
    trim_blocks: false
  tags: [seafile_conf, conf]
- template:
    src: "docker.env"
    dest: "{{cops_seafile_compose_dir}}/docker.env"
    mode: "0640"
    trim_blocks: false
  tags: [seafile_conf, conf]
- blockinfile:
    create: true
    path: "{{cops_seafile_compose_dir}}/.env"
    content: |-
      {{cops_seafile_dotenv}}
      {{cops_seafile_dotenv_extra}}
    marker: "# ANSIBLE MANAGED BLOCK :: deploy commit :: {mark}"
  tags: [seafile_conf, conf]
- name: Create directories
  file:
    path: "{{cops_seafile_compose_dir}}/{{ item.path }}"
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/../../setup/"
  when: item.state == 'directory'
  tags: [seafile_conf, conf]
- name: Template files
  template:
    src: '{{ item.src }}'
    dest: "{{cops_seafile_compose_dir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
    trim_blocks: false
  with_filetree: "{{playbook_dir}}/../../setup/"
  when:
  - "item.state == 'file'"
  - "not item.path|regex_search('\\.frep$|traefik.tom|conf.d')"
  tags: [seafile_conf, conf]
- name: Copy files
  copy:
    src: '{{ item.src }}'
    dest: "{{cops_seafile_compose_dir}}/{{ item.path }}"
    mode: '{{ item.mode }}'
  with_filetree: "{{playbook_dir}}/../../setup/"
  when:
  - "item.state == 'file'"
  - "item.path|regex_search('\\.frep$|traefik.tom|conf.d')"
  tags: [seafile_conf, conf]
- include_tasks: docker_login.yml
  with_items: "{{cops_seafile_registries}}"
- shell: |
    set -ex
    cd "{{cops_seafile_compose_dir}}"
    : {{cops_seafile_dc}} build {{cops_seafile_build_args}}
  when:
  - "cops_seafile_build|copsf_asbool"
  - "cops_seafile_build_args|copsf_asbool"
# ensure all images are (re) pulled
- shell: |
    set -ex
    cd "{{cops_seafile_compose_dir}}"
    {{cops_seafile_dc}} pull {{cops_seafile_pull_args}}
  retries: 5
  delay: 10
  when:
  - "cops_seafile_pull|copsf_asbool"
  tags: [seafile_pull, pull]
- include_tasks: service.yml
  tags: [seafile_service, service]
