version: '3.7'
x-images:
  env: &env
    env_file: [.env, docker.env]
    environment: {"COMPOSE_PROJECT_NAME": "$COMPOSE_PROJECT_NAME"}
x-onlyoffice-base: &onlyofficebase
  <<: [ *env ]
x-onlyoffice: &onlyoffice
  <<: [ *onlyofficebase ]
  image: "onlyoffice/documentserver:latest"
  stdin_open: true
  env_file: [.env, docker.env, onlyoffice.env]
  volumes:
    - onlyoffice-conf:/etc/onlyoffice
    - onlyoffice-data:/var/www/onlyoffice/Data
    - onlyoffice-logs:/var/log/onlyoffice
    - onlyoffice-lib:/var/lib/onlyoffice
    - onlyoffice-cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
    - onlyoffice-samples:/var/www/onlyoffice/documentserver-example/public/files
    - fonts:/usr/share/fonts/custom
services:
  db:
    <<: [ *env ]
    image: "{{cops_seafile_mysql_image}}"
    hostname: seafile-mysql
    volumes:
    - seafile-db:/var/lib/mysql
  setup-services:
    <<: [ *env ]
    image: "{{cops_seafile_mysql_image}}"
    depends_on: [db, memcached]
    entrypoint:
    - /bin/sh
    - '-c'
    - |-
      set -ex
      MYSQL_STARTUP_TIMEOUT=$${MYSQL_STARTUP_TIMEOUT:-45s}
      flag=/started_$$(echo $$MYSQL_DB|sed -re "s![/:]!__!g")
      if [ -e "$$flag" ];then rm -f "$$flag";fi
      echo "Try connection to mysql: $$MYSQL_DB & wait for db init" >&2 \
      && ( while true;do if ( echo "select 1" | mysql );then touch $$flag && break;fi;done )&
      set -x \
      && dockerize -wait file://$$flag -timeout $${MYSQL_STARTUP_TIMEOUT} \
      && : create all needed databases \
      && for i in $$SEAFILE_DB $$SEAHUB_DB $$CCNET_DB;do \
        if ! ( echo "select 1" | mysql $$i );then \
          echo "Creating db $$i"; \
          mysql -e "CREATE DATABASE $$i"; \
        fi; \
      done \
      && set +x \
      && mysql -e \
          "GRANT ALL PRIVILEGES ON $$SEAFILE_DB.* \
              TO '$$SEAFILE_USER'@'%' \
              IDENTIFIED BY '$$MYSQL_PASSWORD';FLUSH PRIVILEGES;" \
      && mysql -e \
          "GRANT ALL PRIVILEGES ON $$SEAHUB_DB.* \
              TO '$$SEAHUB_USER'@'%' \
              IDENTIFIED BY '$$MYSQL_PASSWORD';FLUSH PRIVILEGES;" \
      && mysql -e \
          "GRANT ALL PRIVILEGES ON $CCNET_DB.* \
              TO '$$CCNET_USER'@'%' \
              IDENTIFIED BY '$$MYSQL_PASSWORD';FLUSH PRIVILEGES;" \
      && set -x \
      && while true;do printf "HTTP/1.1 200 OK\n\nstarted"| ( nc -l -p 80 || /bin/true);done
  memcached:
    image: "{{cops_seafile_memcached_image}}"
    hostname: seafile-memcached
    entrypoint: memcached -m 256
  seafile:
    <<: [ *env ]
    image: "{{cops_seafile_image}}"
    command:
    - /bin/bash
    - '-exc'
    - >-
      : \
      && MYSQL_STARTUP_TIMEOUT=$${MYSQL_STARTUP_TIMEOUT:-45s}
      && dockerize -wait http://setup-services -timeout $${MYSQL_STARTUP_TIMEOUT}
      && while read f;do
      echo "Configuring $$f" >&2
      && sed -i -re "s/(rotate )?[0-9]+/rotate ${NGINX_LOGROTATE_DAYS:-365}\s*$$/g" /etc/logrotate.d/nginx
      && frep $$f:/shared/seafile/conf/$$(basename $$f .frep) --overwrite;done < <(
      find /shared/seafile/conftemplates/ -name *frep)
      && cp /shared/seafile/conf/seahub-crontab /etc/cron.d && chmod 600 /etc/cron.d/* && chown root:root /etc/cron.d/*
      && /sbin/my_init -- /scripts/start.py
    volumes:
    - seafile-data:/shared
    - ./conf:/shared/seafile/conftemplates
    depends_on: [setup-services]
  traefik:
    <<: [ *env ]
    image: corpusops/traefik:alpine
    entrypoint:
    - /bin/sh
    - "-exc"
    - |-
      frep /staticconf/traefik.toml:/traefik.toml --overwrite
      traefik \
       --sendanonymoususage=false --defaultentrypoints=http \
       --accesslog --accesslog.bufferingsize=10 --loglevel=info \
       --rest --api --web --web.metrics -c /traefik.toml
    volumes:
    - ./traefik:/staticconf
    ports:
    - "${SEAFILE_HTTP_PORT:-80}:80"
    - "${SEAFILE_HTTPS_PORT:-443}:443"


{% if cops_seafile_onlyoffice_hostname %}
#
# onlyoffice
#
  onlyoffice-documentserver-data:
    <<: [ *onlyoffice ]
    hostname: onlyoffice-documentserver-data
    image: onlyoffice/documentserver:latest
    environment:
      - ONLYOFFICE_DATA_CONTAINER=true

  onlyoffice-documentserver:
    <<: [ *onlyoffice ]
    environment:
      - ONLYOFFICE_DATA_CONTAINER_HOST=onlyoffice-documentserver-data
    expose:
      - '80'
    depends_on:
    - onlyoffice-documentserver-data
    - onlyoffice-postgresql
    - onlyoffice-redis
    - onlyoffice-rabbitmq

  onlyoffice-redis:
    <<: [ *onlyofficebase ]
    hostname: onlyoffice-redis
    image: corpusops/redis:latest
    expose:
      - '6379'

  onlyoffice-rabbitmq:
    <<: [ *onlyofficebase ]
    hostname: onlyoffice-rabbitmq
    image: corpusops/rabbitmq:3.5
    expose:
      - '5672'

  onlyoffice-postgresql:
    <<: [ *onlyofficebase ]
    hostname: onlyoffice-postgresql
    image: corpusops/postgres:12
    environment:
      - POSTGRES_PASSWORD=${ONLYOFFICE_DB_PASSWORD}
      - POSTGRES_DB=${ONLYOFFICE_DB_NAME}
      - POSTGRES_USER=${ONLYOFFICE_DB_USER}
    expose:
      - '5432'
    volumes:
      - onlyoffice-pgsql:/var/lib/postgresql
{% endif %}
{% if cops_seafile_collabora_hostname %}
  # collabora
  collabora:
    <<: [ *env ]
    image: collabora/code
    entrypoint:
    - /bin/bash
    - '-ec'
    - |-
      export password="$$COLLABORA_PASSWORD"
      set -x
      export username="$$COLLABORA_USERNAME"
      export DONT_GEN_SSL_CERT="$$COLLABORA_DONT_GEN_SSL_CERT"
      export server_name="$$COLLABORA_HOSTNAME"
      export domain="$$COLLABORA_DOMAINS"
      export SLEEPFORDEBUGGER="0"
      export dictionaries="$$COLLABORA_DICTS"
      export extra_params="$${extra_params-} --o:net.frame_ancestors=$$SEAFILE_SERVER_HOSTNAME"
      if [ "x$$DONT_GEN_SSL_CERT" != "x" ];then
        export extra_params="$${extra_params-} --o:ssl.enable=false --o:ssl.termination=true"
      fi
      exec bash start-libreoffice.sh
    cap_add: [MKNOD, SYS_CHROOT, FOWNER]
    volumes:
    - fonts:/usr/share/fonts/custom
{% endif %}

volumes:
  fonts:
  seafile-db: {name: "${COMPOSE_PROJECT_NAME}-seafile-db", external: false}
  seafile-data: {name: "${COMPOSE_PROJECT_NAME}-seafile-data", external: false}
{% if cops_seafile_onlyoffice_hostname %}
  # onlyoffice
  onlyoffice-pgsql:
  onlyoffice-data:
  onlyoffice-logs:
  onlyoffice-cache:
  onlyoffice-conf:
  onlyoffice-samples:
  onlyoffice-lib:
{% endif %}
{% if cops_seafile_collabora_hostname %}
  # collabora
{% endif %}
