version: '3.7'
x-images:
  env: &env
    env_file: [.env, docker.env]
    environment: {"COMPOSE_PROJECT_NAME": "$COMPOSE_PROJECT_NAME"}
services:
  db:
    restart: unless-stopped
  memcached:
    restart: unless-stopped
  setup-services:
    restart: unless-stopped
  seafile:
    restart: unless-stopped
  traefik:
    restart: unless-stopped
{% if cops_seafile_onlyoffice_hostname %}
#
# onlyoffice
#
  onlyoffice-documentserver-data:
    restart: unless-stopped
  onlyoffice-documentserver:
    restart: unless-stopped
  onlyoffice-redis:
    restart: unless-stopped
  onlyoffice-rabbitmq:
    restart: unless-stopped
  onlyoffice-postgresql:
    restart: unless-stopped
{% endif %}
{% if cops_seafile_collabora_hostname %}
  # collabora
  collabora:
    restart: unless-stopped
{% endif %}
  backup-db:
    <<: [ *env ]
    image: "corpusops/dbsmartbackup:mariadb-10.1"
    depends_on: [db, memcached]
    volumes:
    - backupdb-dumps:/var/db_smart_backup/
    - backupdb-logs:/var/db_smart_backup/logs/
volumes:
  backupdb-dumps:
  backupdb-logs:
