version: '3.7'
services:
  db:
    restart: unless-stopped
  memcached:
    restart: unless-stopped
  setup-services:
    restart: unless-stopped
  seafile:
    restart: unless-stopped
  traefik:
    restart: unless-stopped
{% if cops_seafile_onlyoffice_hostname %}
#
# onlyoffice
#
  onlyoffice-documentserver-data:
    restart: unless-stopped
  onlyoffice-documentserver:
    restart: unless-stopped
  onlyoffice-redis:
    restart: unless-stopped
  onlyoffice-rabbitmq:
    restart: unless-stopped
  onlyoffice-postgresql:
    restart: unless-stopped
{% endif %}
{% if cops_seafile_collabora_hostname %}
  # collabora
  collabora:
    restart: unless-stopped
{% endif %}
