---
ssh_envs:
  hosts:
    myhost.example.net:

prod-seafile:
  hosts:
    myhost.example.net: {ansible_host: myhost.example.net, ansible_port: "40001"}

prod_loc-seafile:
  hosts:
    prod_loc-seafilehost: {ansible_host: localhost, ansible_connection: local}

prod:
  children:
    prod-seafile:

prod_loc:
  children:
    prod_loc-seafile:

seafile_servers:
  children:
    prod:
    prod_loc:
